/**
 * Status-effect kind id -> display name and polarity, for the log view's status
 * overlay selectors (see `statusDisplayName` in `src/utils/status.ts`).
 *
 * GENERATED — do not edit by hand. Reduced from the Endless Ragnarok status
 * table in the game's own data, keeping the two fields the UI reads.
 * Rows the table leaves unnamed are omitted rather than given a placeholder, so
 * they render as bare hex like any id this build has never heard of.
 *
 * Regenerate whenever the game build changes: kind ids are the table's own
 * explicit `status_id` column (insertion-stable), so a patch that inserts a
 * status leaves every existing id in place.
 */

export type StatusCatalogEntry = {
  name: string;
  /** The table's own `beneficial` flag: true for buffs, false for ailments. */
  beneficial: boolean;
};

const StatusCatalog: Record<number, StatusCatalogEntry> = {
  0: { name: "ATK↑", beneficial: true },
  1: { name: "DEF↑", beneficial: true },
  2: { name: "ATK↓", beneficial: false },
  3: { name: "DEF↓", beneficial: false },
  4: { name: "DMG Cut", beneficial: true },
  5: { name: "Regen", beneficial: true },
  6: { name: "Invincibility", beneficial: true },
  7: { name: "Supplementary DMG", beneficial: true },
  8: { name: "Stout Heart", beneficial: true },
  9: { name: "Mirror Image", beneficial: true },
  10: { name: "Substitute", beneficial: true },
  11: { name: "Covered", beneficial: true },
  17: { name: "Debuff Immunity", beneficial: true },
  18: { name: "Drain", beneficial: true },
  20: { name: "Guts", beneficial: true },
  21: { name: "Strength", beneficial: true },
  22: { name: "Jammed", beneficial: true },
  23: { name: "Critical Hit Rate↑", beneficial: true },
  24: { name: "Hostility↑", beneficial: true },
  25: { name: "Autorevive", beneficial: true },
  26: { name: "Mystic Vortex", beneficial: true },
  27: { name: "Focused", beneficial: true },
  28: { name: "Iron Maiden", beneficial: true },
  29: { name: "Dragonform", beneficial: true },
  30: { name: "Godmight", beneficial: true },
  31: { name: "Undying", beneficial: true },
  32: { name: "Bloodthirst", beneficial: true },
  33: { name: "Phantasmagoria", beneficial: true },
  36: { name: "Abyssal Glory", beneficial: true },
  37: { name: "Max HP↓", beneficial: false },
  38: { name: "Double Tap", beneficial: true },
  41: { name: "Shield", beneficial: true },
  42: { name: "DMG↑", beneficial: true },
  43: { name: "Deadshot", beneficial: true },
  44: { name: "Bring the Thunder", beneficial: true },
  45: { name: "Chromatic Wings", beneficial: true },
  46: { name: "Deathmatch Finale", beneficial: true },
  47: { name: "Näed Nulli", beneficial: true },
  48: { name: "Näed Seitset", beneficial: true },
  49: { name: "Näed Nelja", beneficial: true },
  50: { name: "Rising Nova", beneficial: true },
  51: { name: "DMG↓", beneficial: false },
  52: { name: "Battle Hymn", beneficial: true },
  53: { name: "Play with Fire", beneficial: true },
  54: { name: "Sage", beneficial: true },
  55: { name: "Cardinal", beneficial: true },
  56: { name: "DMG Cap↑", beneficial: true },
  57: { name: "Stackable ATK↑", beneficial: true },
  58: { name: "Stackable DEF↑", beneficial: true },
  59: { name: "Stackable DEF↓", beneficial: false },
  60: { name: "Heliotrope Aura", beneficial: true },
  61: { name: "Enhanced Freeflutter", beneficial: true },
  62: { name: "Enhanced Dawnfly", beneficial: true },
  63: { name: "Kaleidoscope", beneficial: true },
  64: { name: "Dragonsbane Pulse", beneficial: true },
  65: { name: "Dark Zeal", beneficial: true },
  66: { name: "Combat Healer", beneficial: true },
  67: { name: "Stackable ATK↓", beneficial: false },
  68: { name: "Ares Surge", beneficial: true },
  69: { name: "Blade Blue", beneficial: true },
  70: { name: "Super Bull's Eye Blast", beneficial: true },
  71: { name: "Superstar", beneficial: true },
  72: { name: "Sniper Elite", beneficial: true },
  73: { name: "Shell Shock", beneficial: false },
  74: { name: "Noble Order", beneficial: true },
  75: { name: "Diamond Cutter", beneficial: true },
  76: { name: "Divine Justice", beneficial: true },
  77: { name: "Ultrafist", beneficial: true },
  78: { name: "Loving Trust", beneficial: true },
  79: { name: "Spiritbond", beneficial: true },
  81: { name: "Magic Chain", beneficial: false },
  82: { name: "Ebony Glint", beneficial: true },
  83: { name: "Stoked Charge", beneficial: true },
  84: { name: "Skill DMG↑", beneficial: true },
  85: { name: "Molten Edge", beneficial: true },
  86: { name: "Super Collapse", beneficial: true },
  87: { name: "Arts Superiór", beneficial: true },
  88: { name: "Grynoth Unleashed", beneficial: true },
  89: { name: "Flash Cut", beneficial: true },
  90: { name: "Payback", beneficial: true },
  91: { name: "Heroic Vigor", beneficial: true },
  92: { name: "Truth", beneficial: true },
  93: { name: "Synergy Boost", beneficial: true },
  94: { name: "Loop Master", beneficial: true },
  95: { name: "Arvess Unleashed", beneficial: true },
  96: { name: "Heavy Hammer", beneficial: true },
  97: { name: "Spiral Rose Bloomed", beneficial: true },
  98: { name: "Lost Love Bloomed", beneficial: true },
  99: { name: "Näed Nulli Excel", beneficial: true },
  100: { name: "Näed Seitset Excel", beneficial: true },
  101: { name: "Näed Nelja Excel", beneficial: true },
  102: { name: "Embrasque Unleashed", beneficial: true },
  103: { name: "Enhanced Damage Skills", beneficial: true },
  104: { name: "Enhanced Combo Finishers", beneficial: true },
  105: { name: "Avalanche", beneficial: true },
  106: { name: "Limitless Light", beneficial: true },
  107: { name: "Lucent Refuge", beneficial: true },
  108: { name: "Bell of War", beneficial: false },
  109: { name: "Piercing Gleam", beneficial: true },
  110: { name: "Dawnray", beneficial: true },
  111: { name: "Dull Point", beneficial: false },
  112: { name: "Ultimatum", beneficial: true },
  113: { name: "Fall Flat", beneficial: false },
  114: { name: "Wild Showman", beneficial: true },
  115: { name: "Daredevil", beneficial: true },
  116: { name: "Sovereign", beneficial: true },
  117: { name: "Star Sea", beneficial: true },
  118: { name: "Flamek Unleashed", beneficial: true },
  119: { name: "Enhanced Upright", beneficial: true },
  120: { name: "Enhanced Reversed", beneficial: true },
  121: { name: "Enhanced Upright+", beneficial: true },
  122: { name: "Enhanced Reversed+", beneficial: true },
  123: { name: "Enhanced Combo Finishers", beneficial: true },
  124: { name: "Malice", beneficial: true },
  125: { name: "Pincer Synergy", beneficial: true },
  126: { name: "Inversa", beneficial: false },
  127: { name: "Enhanced Clincher", beneficial: true },
  128: { name: "Rise of Justice", beneficial: true },
  129: { name: "Pain of Death", beneficial: true },
  130: { name: "Kiss of the Devil", beneficial: true },
  131: { name: "Collapse of the Tower", beneficial: true },
  132: { name: "Melody of Judgement", beneficial: true },
  133: { name: "Samudaya", beneficial: true },
  134: { name: "Stun Resistance↓", beneficial: false },
  135: { name: "Charisma", beneficial: true },
  136: { name: "Booming Beatdown", beneficial: true },
  137: { name: "Flame Wolf", beneficial: true },
  138: { name: "Blood-Drinking Blade", beneficial: true },
  139: { name: "Dual Raid", beneficial: true },
  140: { name: "Burn Immunity", beneficial: true },
  141: { name: "Frostbite/Glaciate Immunity", beneficial: true },
  142: { name: "Rooted", beneficial: true },
  144: { name: "Daybreak", beneficial: true },
  145: { name: "Unstable", beneficial: false },
  146: { name: "Proto-White World", beneficial: true },
  147: { name: "Fractured World", beneficial: false },
  148: { name: "Chaos Shift", beneficial: true },
  149: { name: "Fractured World", beneficial: false },
  1000: { name: "Poison", beneficial: false },
  1001: { name: "Burn", beneficial: false },
  1002: { name: "Slow", beneficial: false },
  1003: { name: "Dizzy", beneficial: false },
  1004: { name: "Glaciate", beneficial: false },
  1005: { name: "Frostbite", beneficial: false },
  1006: { name: "Sandtomb", beneficial: false },
  1007: { name: "Paralysis", beneficial: false },
  1008: { name: "Held Under", beneficial: false },
  1011: { name: "Darkflame", beneficial: false },
  1012: { name: "Bound", beneficial: false },
  1015: { name: "Bound", beneficial: false },
  1016: { name: "Skill Sealed", beneficial: false },
  1017: { name: "SBA Sealed", beneficial: false },
  1018: { name: "Blight", beneficial: false },
  1019: { name: "Petrified", beneficial: false },
  1020: { name: "Arvess Fermare", beneficial: false },
  1021: { name: "Elemental Friction", beneficial: false },
};

export default StatusCatalog;
